### ISSUE TITLE
Add Project Reactor version

### ISSUE THREAD

**Issue by MGathier** [AxonFramework/axon-bom#11]
### Enhancement Description

Add dependencies for reactor as there are issues when using incorrect version of reactor.

### Current Behaviour

User has to specify the version of reactor in their own pom file, potentially leading to issues when upgrading from older Axon version.

**Comment by smcvb** [comment]
Closing this issue, as it has been resolved in pull request #43.
Furthermore, updated the title to specify this predicament's around Project Reactor instead of external dependencies in general.
