### ISSUE TITLE
Support Axon 4.7

### ISSUE THREAD

**Issue by williancolognesitrimble** [AxonFramework/axon-bom#112]
### Feature Description

Hello, Looks like all dependencies related to this bom are already updated to axon 4.7, when will it be available to be used?

Thanks.

### Current Behaviour

Just released til version 4.6.3

### Wanted Behaviour

Release support to version 4.7.x

### Possible Workarounds

Put the versions directly in dependencies without bom to auto-fill the versions.

**Comment by smcvb** [comment]
The aim was today, @williancolognesitrimble. In all honesty, hoped dependabot would pick up the versions and construct PRs for all new versions. 
For some reason, it stopped making PRs for Axon Framework organization repositories...
If you have a hunch why know your input is much appreciated.
