### ISSUE TITLE
Is the old version of protobuf-java (3.25.1) a hard requirement?

### ISSUE THREAD

**Issue by magnusheino** [AxonFramework/axon-bom#187]
### Basic information

* Axon BOM version: 4.10

<img width="338" alt="{DA4867EC-4589-4C7E-9F92-391E3F8CC9E2}" src="https://github.com/user-attachments/assets/28618659-c03e-4d55-92a8-427789e72b2a">

I have a problem with 3.25.1 being old, and other dependencies are starting to use 4 (com.netflix.graphql from the dgs framework)... is there a plan to upgrade, or can I pull in other deps to have it solved right now (since i noticed that there are some newer releases available than what the bom pulls).

Right now it seems that pinning the version to 3.25.1 solves it, but I guess one day it will be too old for other deps...

**Comment by smcvb** [comment]
Thanks for nudging us the descrepancy you're facing with other dependencies, @magnusheino.

As you already show in your graph, Axon **does not** depend on the mentioned dependency, `protobuf-java`.
We use `grpc-protobuf` to do the communication between Axon Server and Axon Framework, and I would not recommend anybody change the `protobuf-java` version.
We simply cannot vouch for the workings of the `grpc-protobuf` version if you do, making it a decision we cannot make for others.

Although I understand `protobuf-java` is already at version 4.29.1, the latest `grpc-protobuf` version (1.69.0) is still on the latest 3.x version of `protobuf-java`, being 3.25.5.

So, if you're using Axon Server, there isn't that much I can suggest you to do, @magnusheino.
If you're not using Axon Server, you're free to exclude the `axonserver-connector-java` module from the dependencies.

Besides the rightful, yet unresolvable remark, I have changed the type of this issue from "bug" to "dependency upgrade," is this isn't a bug issue.
Furthermore, I'll keep this issue open, as we (obviously) do desire to go to a newer version.
We just have to wait until `grpc-protobuf` chooses to upgrade.

Concluding, sorry for any inconvenience here, @magnusheino, but I am afraid we're tied here.
If you do figure out, or know, a way around this, your input would be very much appreciated.

**Comment by magnusheino** [comment]
It turned out that the component that required a newer version in my application was a component that I wasn't using. So for now I removed it with an exclude in the pom file. grpc-protobuf will probably upgrade eventually and solve the problem. Thanks for an articulate, accurate and informative reply, as always Steven :-)

**Comment by smcvb** [comment]
Ah nice, that's a relief to hear, @magnusheino!
And, of course, glad to help out!!

Given that the issue's resolved for you and (I agree with you hear) the likely chance that grpc-protobuf will eventually upgrade as well, I trust that our dependabot settings will do the rest.
As such, I feel comfortable enough to close the issue for now.
If something changes concerning this topic, I'll be sure to reopen this ticket.
