### ISSUE TITLE
add axon-server-plugin-api

### ISSUE THREAD

**Issue by jangalinski** [AxonFramework/axon-bom#20]
### Feature Description

I would like to have the latest version of the server plugin api in this BOM as well

```
<!-- https://mvnrepository.com/artifact/io.axoniq/axonserver-plugin-api -->
<dependency>
    <groupId>io.axoniq</groupId>
    <artifactId>axonserver-plugin-api</artifactId>
    <version>4.5</version>
</dependency>
```

**Comment by smcvb** [comment]
Great suggestions @jangalinski! Just resolved this issue, which will make it a part of `axon-bom` 4.5.3
